services:

  python:
    build: ./
    container_name: python-python
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
